/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {type: 'doc', id: 'index', label: 'Home'},
    {type: 'doc', id: 'overview', label: 'What is OPTI?'},
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/basics',
        'getting-started/overloads',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: false,
      link: {type: 'doc', id: 'examples/index'},
      items: [
        {
          type: 'category',
          label: 'Problem types',
          collapsed: true,
          items: [
            'examples/problem-types/lp',
            'examples/problem-types/milp',
            'examples/problem-types/qp',
            'examples/problem-types/miqp',
            'examples/problem-types/qcqp',
            'examples/problem-types/miqcqp',
            'examples/problem-types/sdp',
            'examples/problem-types/snle',
            'examples/problem-types/scnle',
            'examples/problem-types/nls',
            'examples/problem-types/model-fit',
            'examples/problem-types/nlp',
            'examples/problem-types/gnlp',
            'examples/problem-types/minlp',
          ],
        },
        {
          type: 'category',
          label: 'Dynamic optimization',
          collapsed: true,
          items: [
            'examples/dynamic-optimization/dnls',
            'examples/dynamic-optimization/opts',
          ],
        },
        {
          type: 'category',
          label: 'File formats',
          collapsed: true,
          items: [
            'examples/file-formats/mps',
            'examples/file-formats/ampl',
            'examples/file-formats/sdpa',
            'examples/file-formats/gams',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Modelling and solving',
          collapsed: true,
          items: [
            'guides/advanced/opts',
            'guides/advanced/adv-opt',
            'guides/advanced/plots',
            'guides/advanced/multi-solve',
            'guides/advanced/sym-builder',
            'guides/advanced/white-box',
            'guides/advanced/large-scale',
            'guides/advanced/cons',
            'guides/advanced/low-level',
            'guides/advanced/deriv1',
            'guides/advanced/deriv2',
          ],
        },
        {
          type: 'category',
          label: 'Integer programming',
          collapsed: true,
          items: [
            'guides/integer-programming/tricks',
            'guides/integer-programming/sos',
          ],
        },
        {
          type: 'category',
          label: 'Option reference',
          collapsed: true,
          items: [
            'reference/options/optiset',
            'reference/options/optidynset',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Solver reference',
      collapsed: true,
      link: {type: 'doc', id: 'solvers/index'},
      items: [
        'solvers/baron',
        'solvers/bonmin',
        'solvers/cbc',
        'solvers/clp',
        'solvers/cplex',
        'solvers/csdp',
        'solvers/dsdp',
        'solvers/filtersd',
        'solvers/glpk',
        'solvers/gmatlab',
        'solvers/hybrj',
        'solvers/ipopt',
        'solvers/l-bfgs-b',
        'solvers/levmar',
        'solvers/lipsol',
        'solvers/lmder',
        'solvers/lpsolve',
        'solvers/m1-qn3',
        'solvers/matlab',
        'solvers/mkltrnls',
        'solvers/mosek',
        'solvers/mumps',
        'solvers/nl2-sol',
        'solvers/nlopt',
        'solvers/nomad',
        'solvers/ooqp',
        'solvers/pswarm',
        'solvers/qsopt',
        'solvers/scip',
        'solvers/sedumi',
      ],
    },
    {
      type: 'category',
      label: 'Utilities',
      collapsed: true,
      link: {type: 'doc', id: 'reference/utilities/index'},
      items: [
        'reference/utilities/adiff',
        'reference/utilities/asl',
        'reference/utilities/coin-utils',
        'reference/utilities/cpp-ad',
        'reference/utilities/djacobi',
        'reference/utilities/r-math-lib',
      ],
    },
    {
      type: 'category',
      label: 'Project information',
      collapsed: true,
      items: [
        'project/download',
        'project/academic-extension',
        'project/citation',
        'project/faq',
        'project/license',
      ],
    },
  ],
};

module.exports = sidebars;
